import type { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: 1,
    title: 'Spaghetti Carbonara',
    description: 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
    prepTime: '20 minutes',
    image: 'https://picsum.photos/seed/101/600/400',
    imageHint: 'spaghetti carbonara',
    ingredients: [
      { name: 'spaghetti', quantity: '400g' },
      { name: 'pancetta', quantity: '150g' },
      { name: 'garlic', quantity: '2 cloves' },
      { name: 'eggs', quantity: '2 large' },
      { name: 'parmesan cheese', quantity: '50g' },
      { name: 'black pepper', quantity: 'to taste' },
    ],
    instructions: [
      'Cook spaghetti according to package directions.',
      'While pasta is cooking, heat olive oil in a large skillet over medium heat. Add pancetta and cook until crisp.',
      'Add garlic to the skillet and cook for 1 minute until fragrant.',
      'In a bowl, whisk together eggs and parmesan cheese.',
      'Drain pasta and add it to the skillet with the pancetta. Toss to combine. Remove from heat.',
      'Pour the egg and cheese mixture over the pasta, stirring quickly to create a creamy sauce. Season with black pepper and serve immediately.',
    ],
  },
  {
    id: 2,
    title: 'Chicken Stir-Fry',
    description: 'A quick and healthy stir-fry with tender chicken and fresh vegetables in a savory sauce.',
    prepTime: '25 minutes',
    image: 'https://picsum.photos/seed/102/600/400',
    imageHint: 'chicken stirfry',
    ingredients: [
      { name: 'chicken breast', quantity: '2' },
      { name: 'broccoli', quantity: '1 head' },
      { name: 'bell pepper', quantity: '1' },
      { name: 'onion', quantity: '1' },
      { name: 'soy sauce', quantity: '1/4 cup' },
      { name: 'ginger', quantity: '1 tbsp, grated' },
      { name: 'garlic', quantity: '2 cloves, minced' },
      { name: 'rice', quantity: 'for serving' },
    ],
    instructions: [
      'Cut chicken into bite-sized pieces. Chop broccoli, bell pepper, and onion.',
      'In a small bowl, mix soy sauce, ginger, and garlic.',
      'Heat oil in a wok or large skillet over high heat. Add chicken and cook until browned.',
      'Add vegetables to the wok and stir-fry for 3-5 minutes until crisp-tender.',
      'Pour the sauce over the chicken and vegetables. Cook for another 1-2 minutes until the sauce has thickened slightly.',
      'Serve hot over a bed of steamed rice.',
    ],
  },
  {
    id: 3,
    title: 'Caprese Salad',
    description: 'A simple and refreshing Italian salad, made of sliced fresh mozzarella, tomatoes, and sweet basil.',
    prepTime: '10 minutes',
    image: 'https://picsum.photos/seed/103/600/400',
    imageHint: 'caprese salad',
    ingredients: [
      { name: 'tomatoes', quantity: '4 ripe' },
      { name: 'fresh mozzarella', quantity: '200g' },
      { name: 'fresh basil', quantity: '1 bunch' },
      { name: 'olive oil', quantity: '2 tbsp' },
      { name: 'balsamic glaze', quantity: '1 tbsp' },
      { name: 'salt', quantity: 'to taste' },
      { name: 'black pepper', quantity: 'to taste' },
    ],
    instructions: [
      'Slice the tomatoes and mozzarella into 1/4-inch thick slices.',
      'Arrange alternating slices of tomato and mozzarella on a platter.',
      'Tuck fresh basil leaves in between the slices.',
      'Drizzle with olive oil and balsamic glaze.',
      'Season with salt and pepper to taste.',
      'Serve immediately to enjoy the fresh flavors.',
    ],
  },
  {
    id: 4,
    title: 'Hearty Lentil Soup',
    description: 'A nutritious and comforting soup packed with lentils, vegetables, and savory herbs.',
    prepTime: '45 minutes',
    image: 'https://picsum.photos/seed/104/600/400',
    imageHint: 'lentil soup',
    ingredients: [
      { name: 'brown lentils', quantity: '1 cup' },
      { name: 'carrots', quantity: '2' },
      { name: 'celery', quantity: '2 stalks' },
      { name: 'onion', quantity: '1' },
      { name: 'garlic', quantity: '3 cloves' },
      { name: 'vegetable broth', quantity: '6 cups' },
      { name: 'diced tomatoes', quantity: '1 can (14.5 oz)' },
      { name: 'thyme', quantity: '1 tsp' },
      { name: 'bay leaf', quantity: '1' },
      { name: 'spinach', quantity: '2 cups' },
    ],
    instructions: [
      'Rinse lentils. Finely chop carrots, celery, and onion. Mince garlic.',
      'In a large pot or Dutch oven, heat olive oil over medium heat. Add onion, carrots, and celery and cook until softened, about 5 minutes.',
      'Stir in garlic and cook for another minute until fragrant.',
      'Add the vegetable broth, lentils, diced tomatoes, thyme, and bay leaf. Bring to a boil.',
      'Reduce heat, cover, and simmer for 30-40 minutes, or until lentils are tender.',
      'Remove the bay leaf. Stir in the spinach and cook until wilted, about 2-3 minutes.',
      'Season with salt and pepper to taste and serve hot.',
    ],
  },
];
